<a href="https://colab.research.google.com/github/a01820205-coder/tc1002_semana_tec/blob/main/TareaNP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Actividad de Numpy

In [ ]:
import numpy as np

In [ ]:
#Crea un arreglo de 10 cincos
lista=[5,5,5,5,5,5,5,5,5,5]
arreglo = np.array(lista)
print(arreglo)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
##Crea un arreglo de enteros pares desde 10, inclusive, hasta 50, inclusive.
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
#Crea una matriz cuadrada de 4 por 4 de números enteros aleatorios.
arreglo= np.random.randint(1,100,16)
arreglo.reshape(4,4)

array([[29,  6, 74, 59],
       [75, 57, 30, 22],
       [ 2, 39, 31,  5],
       [19, 92, 74, 27]])

In [ ]:
#Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula la suma de todos sus elementos.
arreglo= np.random.rand(10)
print(arreglo.sum())

4.375680063256961


In [ ]:
#Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula su media.
arreglo= np.random.rand(10)
print(arreglo.mean())

0.47730385248120777


Actividad de Pandas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Dataframe ficiticio de ventas de frutas
df= pd.DataFrame({'Product':['Çarrots','Broccoli','Banana','Banana','Beans','Orange','Broccoli','Banana'],
                  'Category':['Vegetable','Vegeteable','Fruit','Fruit','Vegetable','Fruit','Vegetable','Fruit'],
                  'Quantify':[8,5,3,4,5,9,11,8],
                  'Amount':[270,239,617,384,626,610,62,90]})
print(df)

    Product    Category  Quantify  Amount
0   Çarrots   Vegetable         8     270
1  Broccoli  Vegeteable         5     239
2    Banana       Fruit         3     617
3    Banana       Fruit         4     384
4     Beans   Vegetable         5     626
5    Orange       Fruit         9     610
6  Broccoli   Vegetable        11      62
7    Banana       Fruit         8      90


In [ ]:
# Selecciona e imprime las columnas de Product y Quantity.
df[['Product','Quantify']]

Product  Quantify
0   Çarrots         8
1  Broccoli         5
2    Banana         3
3    Banana         4
4     Beans         5
5    Orange         9
6  Broccoli        11
7    Banana         8

In [ ]:
#Selecciona e imprime los renglones con índices 4 y 6.
df.iloc[[4,6]]

Product   Category  Quantify  Amount
4     Beans  Vegetable         5     626
6  Broccoli  Vegetable        11      62

In [ ]:
#.Usando el método groupby, agrupa usando la columna Product y muestra la suma de la columna Quantity.
Producto= df.groupby("Product")
print(Producto)

In [ ]:
print(Producto['Quantify'])

In [ ]:
Producto['Quantify'].sum()

Product
Banana      15
Beans        5
Broccoli    16
Orange       9
Çarrots      8
Name: Quantify, dtype: int64

In [ ]:
#Usando el método groupby, agrupa usando la columna Categoryy muestra la suma de la columna Amount.
Categoría= df.groupby("Category")
print(Categoría)

In [ ]:
print(Categoría['Amount'])

In [ ]:
Categoría['Amount'].sum()

Category
Fruit         1701
Vegetable      958
Vegeteable     239
Name: Amount, dtype: int64